### PR TITLE
Made FK

### LINKED ISSUE #11: FK Link Models
Make FK link from user and jwttoken (dbcontext and models)

### PR DESCRIPTION
**Pull request by mfhum**

### CODE REVIEW

**Comment by mfhum** [comment]
@baltermia pls review

**Comment by mfhum** [comment]
@baltermia works fully, ready to merch after your approval

**Comment by baltermia** [comment]
Did you create a new migration or did you override the existing `Init`?

**Comment by mfhum** [comment]
new migration

**Comment by baltermia** [comment]
did you commit it? I dont see any new files in the pr

**Comment by mfhum** [comment]
it's on somehow no changes then :) so all good to merge

**Comment by baltermia** [comment]
I think the changes for the Foreign Key were added to the `Init` migration, I don't even know how that is possible lol
I can't run it on my machine since the database created is based on the old Init migration, and it's now trying to apply the same migration (same name, so it doesn't have the correct context and version history) with the new settings.
Could you revert the changes from the `Init` migration and add them as a new migration?

The Data Project does an automatic Migration at the start of the application:
```csharp
context.Database.Migrate(); // this throws an exception, saying the User database exists already - which is true
// if there were a new migration, it wouldn't try to create the User table, but edit it and add the FK
```

I guess you've migrated it manually in the NuGet Console, therefore you didn't get any runtime exceptions.

**Comment by baltermia** [comment]
You can check the [Files Changed](https://github.com/Humteria/humteria-backend/pull/14/files) Tab, the foreign key changes were added to the init migration

**Comment by mfhum** [comment]
yes I did it manually, dont quite get how to fix it

**Comment by mfhum** [comment]
add a new migration?

**Review by baltermia — CHANGES_REQUESTED** [review]
Create new migration instead of altering existing init migration

**Comment by baltermia** [comment]
yeah exactly, I think you should just revert the changes on the init migration files and create a new one in the package manager console. 
Should I do it for you though, I know how to fix it?

**Comment by mfhum** [comment]
tested it locally, works fully even with initialisation of db, are your connections strings correct?

**Comment by mfhum** [comment]
@baltermia please make sure that your connectionstrings are correct, I dont get any errors even after further testing with the exact state of the reverted and not reverted commit.

**Comment by baltermia** [comment]
the problem is that changing an existing migration will mess up the entire migration history and existing databases since they are linked to specific migrations. I'm gonna fix it in a minute

**Comment by baltermia** [comment]
I'm just gonna let you merge it. if I change the migrations again, you will have the same problems I'm facing now. I'm gonna explain it to you in the evening, will you be online?

**Review by baltermia — APPROVED** [review]

**Comment by mfhum** [comment]
so in the future, I will make a new migration, got it :), got uni tonight

**Pull request merged**
